Update Plugin.php
hiqdev/composer-config-plugin pull request #7
Opened 2018-07-30 11:13 UTC by jomonkj

#6 fIX

2018-07-30 12:13 UTC, hiqsol commented
Ok, thank you.
Good idea, I'll take it soon.

2018-07-30 16:20 UTC, SilverFire requested changes

2018-07-30 16:20 UTC, SilverFire commented on src/Plugin.php
> +        return (json_decode(@file_get_contents($path), true))['extra'] ?? [];
@hiqsol I think it makes sense to load that composer.json into a Package object

2018-07-30 16:45 UTC, hiqsol commented
I think to extract all package related logic to `Package` class wrapper around composer Package class.

Apropos, development moved to 1.0 branch - master is freezed.

@jomonkj do you need this change now? I'll do it. But later. Ok?

2018-07-30 17:05 UTC, jomonkj commented
Ok, Great
but if you accept this changes for temporary, it will help me to the hidev implementation to my projects

2018-07-31 08:13 UTC, hiqsol commented
Ok :)
I've managed to merge 1.0 to master and it seems to work.
I'll implement reading extra from file soon (today).

2018-07-31 09:43 UTC, hiqsol commented
I've rewritten package logic to prefer data from `composer.json` where suitable.
Should be fine now. So closing this.

2018-07-31 09:43 UTC, closed without merging